// Code generated by tools/generate_contract.py; DO NOT EDIT.
package agenthttp

import (
	"time"
	"wind/backend/internal/domain"
)

func ForecastRequestFromDomain(v domain.ForecastRequest) ForecastRequest {
	out := ForecastRequest{}
	out.ForecastOrigin = v.ForecastOrigin.UTC()
	out.HorizonHours = v.HorizonHours
	out.TurbineIDs = make([]int, len(v.TurbineIDs))
	for i, item := range v.TurbineIDs {
		out.TurbineIDs[i] = item
	}
	out.ModelVersion = v.ModelVersion
	out.Mode = v.Mode
	out.DataMode = v.DataMode
	return out
}
func ForecastRequestToDomain(v ForecastRequest) domain.ForecastRequest {
	out := domain.ForecastRequest{}
	out.ForecastOrigin = v.ForecastOrigin.UTC()
	out.HorizonHours = v.HorizonHours
	out.TurbineIDs = make([]int, len(v.TurbineIDs))
	for i, item := range v.TurbineIDs {
		out.TurbineIDs[i] = item
	}
	out.ModelVersion = v.ModelVersion
	out.Mode = v.Mode
	out.DataMode = v.DataMode
	return out
}
func ReplayRequestFromDomain(v domain.ReplayRequest) ReplayRequest {
	out := ReplayRequest{}
	out.Origins = make([]time.Time, len(v.Origins))
	for i, item := range v.Origins {
		out.Origins[i] = item.UTC()
	}
	out.HorizonHours = v.HorizonHours
	out.TurbineIDs = make([]int, len(v.TurbineIDs))
	for i, item := range v.TurbineIDs {
		out.TurbineIDs[i] = item
	}
	out.ModelVersion = v.ModelVersion
	out.DataMode = v.DataMode
	return out
}
func ReplayRequestToDomain(v ReplayRequest) domain.ReplayRequest {
	out := domain.ReplayRequest{}
	out.Origins = make([]time.Time, len(v.Origins))
	for i, item := range v.Origins {
		out.Origins[i] = item.UTC()
	}
	out.HorizonHours = v.HorizonHours
	out.TurbineIDs = make([]int, len(v.TurbineIDs))
	for i, item := range v.TurbineIDs {
		out.TurbineIDs[i] = item
	}
	out.ModelVersion = v.ModelVersion
	out.DataMode = v.DataMode
	return out
}
func JobRecordFromDomain(v domain.JobRecord) JobRecord {
	out := JobRecord{}
	out.JobID = v.JobID
	out.JobType = v.JobType
	out.Status = v.Status
	out.CreatedAt = v.CreatedAt.UTC()
	out.UpdatedAt = v.UpdatedAt.UTC()
	out.Stage = v.Stage
	if v.ErrorCode != nil {
		item := *v.ErrorCode
		out.ErrorCode = &item
	}
	if v.ErrorMessage != nil {
		item := *v.ErrorMessage
		out.ErrorMessage = &item
	}
	return out
}
func JobRecordToDomain(v JobRecord) domain.JobRecord {
	out := domain.JobRecord{}
	out.JobID = v.JobID
	out.JobType = v.JobType
	out.Status = v.Status
	out.CreatedAt = v.CreatedAt.UTC()
	out.UpdatedAt = v.UpdatedAt.UTC()
	out.Stage = v.Stage
	if v.ErrorCode != nil {
		item := *v.ErrorCode
		out.ErrorCode = &item
	}
	if v.ErrorMessage != nil {
		item := *v.ErrorMessage
		out.ErrorMessage = &item
	}
	return out
}
func ForecastPointFromDomain(v domain.ForecastPoint) ForecastPoint {
	out := ForecastPoint{}
	out.TurbineID = v.TurbineID
	out.ValidTime = v.ValidTime.UTC()
	out.IntervalEnd = v.IntervalEnd.UTC()
	out.LeadHours = v.LeadHours
	out.PowerMean = v.PowerMean
	out.Q10 = v.Q10
	out.Q50 = v.Q50
	out.Q90 = v.Q90
	return out
}
func ForecastPointToDomain(v ForecastPoint) domain.ForecastPoint {
	out := domain.ForecastPoint{}
	out.TurbineID = v.TurbineID
	out.ValidTime = v.ValidTime.UTC()
	out.IntervalEnd = v.IntervalEnd.UTC()
	out.LeadHours = v.LeadHours
	out.PowerMean = v.PowerMean
	out.Q10 = v.Q10
	out.Q50 = v.Q50
	out.Q90 = v.Q90
	return out
}
func WeatherProvenanceFromDomain(v domain.WeatherProvenance) WeatherProvenance {
	out := WeatherProvenance{}
	out.Provider = v.Provider
	out.RunID = v.RunID
	out.InitializationTime = v.InitializationTime.UTC()
	out.EffectiveAvailableAt = v.EffectiveAvailableAt.UTC()
	out.AvailabilityBasis = v.AvailabilityBasis
	if v.AvailabilityPolicyID != nil {
		item := *v.AvailabilityPolicyID
		out.AvailabilityPolicyID = &item
	}
	out.RetrievedAt = v.RetrievedAt.UTC()
	out.SourceReference = v.SourceReference
	out.ContentSHA256 = v.ContentSHA256
	return out
}
func WeatherProvenanceToDomain(v WeatherProvenance) domain.WeatherProvenance {
	out := domain.WeatherProvenance{}
	out.Provider = v.Provider
	out.RunID = v.RunID
	out.InitializationTime = v.InitializationTime.UTC()
	out.EffectiveAvailableAt = v.EffectiveAvailableAt.UTC()
	out.AvailabilityBasis = v.AvailabilityBasis
	if v.AvailabilityPolicyID != nil {
		item := *v.AvailabilityPolicyID
		out.AvailabilityPolicyID = &item
	}
	out.RetrievedAt = v.RetrievedAt.UTC()
	out.SourceReference = v.SourceReference
	out.ContentSHA256 = v.ContentSHA256
	return out
}
func ForecastResultFromDomain(v domain.ForecastResult) ForecastResult {
	out := ForecastResult{}
	out.RunID = v.RunID
	out.ForecastOrigin = v.ForecastOrigin.UTC()
	out.HorizonHours = v.HorizonHours
	out.TurbineIDs = make([]int, len(v.TurbineIDs))
	for i, item := range v.TurbineIDs {
		out.TurbineIDs[i] = item
	}
	out.DataMode = v.DataMode
	out.ModelVersion = v.ModelVersion
	out.FeatureVersion = v.FeatureVersion
	out.TrainingDataAvailableThrough = v.TrainingDataAvailableThrough.UTC()
	out.QualityStatus = v.QualityStatus
	out.ExplanationStatus = v.ExplanationStatus
	out.Explanation = v.Explanation
	out.Warnings = make([]string, len(v.Warnings))
	for i, item := range v.Warnings {
		out.Warnings[i] = item
	}
	out.WeatherRuns = make([]WeatherProvenance, len(v.WeatherRuns))
	for i, item := range v.WeatherRuns {
		out.WeatherRuns[i] = WeatherProvenanceFromDomain(item)
	}
	out.Points = make([]ForecastPoint, len(v.Points))
	for i, item := range v.Points {
		out.Points[i] = ForecastPointFromDomain(item)
	}
	return out
}
func ForecastResultToDomain(v ForecastResult) domain.ForecastResult {
	out := domain.ForecastResult{}
	out.RunID = v.RunID
	out.ForecastOrigin = v.ForecastOrigin.UTC()
	out.HorizonHours = v.HorizonHours
	out.TurbineIDs = make([]int, len(v.TurbineIDs))
	for i, item := range v.TurbineIDs {
		out.TurbineIDs[i] = item
	}
	out.DataMode = v.DataMode
	out.ModelVersion = v.ModelVersion
	out.FeatureVersion = v.FeatureVersion
	out.TrainingDataAvailableThrough = v.TrainingDataAvailableThrough.UTC()
	out.QualityStatus = v.QualityStatus
	out.ExplanationStatus = v.ExplanationStatus
	out.Explanation = v.Explanation
	out.Warnings = make([]string, len(v.Warnings))
	for i, item := range v.Warnings {
		out.Warnings[i] = item
	}
	out.WeatherRuns = make([]domain.WeatherProvenance, len(v.WeatherRuns))
	for i, item := range v.WeatherRuns {
		out.WeatherRuns[i] = WeatherProvenanceToDomain(item)
	}
	out.Points = make([]domain.ForecastPoint, len(v.Points))
	for i, item := range v.Points {
		out.Points[i] = ForecastPointToDomain(item)
	}
	return out
}
func AgentEventFromDomain(v domain.AgentEvent) AgentEvent {
	out := AgentEvent{}
	out.EventID = v.EventID
	out.JobID = v.JobID
	out.RecordedAt = v.RecordedAt.UTC()
	out.Kind = v.Kind
	out.Node = v.Node
	out.Message = v.Message
	out.EvidenceRefs = make([]string, len(v.EvidenceRefs))
	for i, item := range v.EvidenceRefs {
		out.EvidenceRefs[i] = item
	}
	return out
}
func AgentEventToDomain(v AgentEvent) domain.AgentEvent {
	out := domain.AgentEvent{}
	out.EventID = v.EventID
	out.JobID = v.JobID
	out.RecordedAt = v.RecordedAt.UTC()
	out.Kind = v.Kind
	out.Node = v.Node
	out.Message = v.Message
	out.EvidenceRefs = make([]string, len(v.EvidenceRefs))
	for i, item := range v.EvidenceRefs {
		out.EvidenceRefs[i] = item
	}
	return out
}
func ApiErrorFromDomain(v domain.ApiError) ApiError {
	out := ApiError{}
	out.Code = v.Code
	out.Message = v.Message
	if v.RequestID != nil {
		item := *v.RequestID
		out.RequestID = &item
	}
	return out
}
func ApiErrorToDomain(v ApiError) domain.ApiError {
	out := domain.ApiError{}
	out.Code = v.Code
	out.Message = v.Message
	if v.RequestID != nil {
		item := *v.RequestID
		out.RequestID = &item
	}
	return out
}
func CapabilitiesFromDomain(v domain.Capabilities) Capabilities {
	out := Capabilities{}
	out.Forecast = v.Forecast
	out.Replay = v.Replay
	out.Cancel = v.Cancel
	out.SSE = v.SSE
	out.WeatherDetails = v.WeatherDetails
	out.SHAP = v.SHAP
	out.Evaluations = v.Evaluations
	out.DataQuality = v.DataQuality
	out.Simulated = v.Simulated
	return out
}
func CapabilitiesToDomain(v Capabilities) domain.Capabilities {
	out := domain.Capabilities{}
	out.Forecast = v.Forecast
	out.Replay = v.Replay
	out.Cancel = v.Cancel
	out.SSE = v.SSE
	out.WeatherDetails = v.WeatherDetails
	out.SHAP = v.SHAP
	out.Evaluations = v.Evaluations
	out.DataQuality = v.DataQuality
	out.Simulated = v.Simulated
	return out
}
func MetaFromDomain(v domain.Meta) Meta {
	out := Meta{}
	out.Service = v.Service
	out.Version = v.Version
	out.ContractVersion = v.ContractVersion
	out.AgentMode = v.AgentMode
	out.AllowedDataModes = make([]string, len(v.AllowedDataModes))
	for i, item := range v.AllowedDataModes {
		out.AllowedDataModes[i] = item
	}
	out.DisplayTimezone = v.DisplayTimezone
	out.SourceTimezoneStatus = v.SourceTimezoneStatus
	out.TargetUnit = v.TargetUnit
	out.NormalizationStatus = v.NormalizationStatus
	out.AgentDependency = v.AgentDependency
	out.Capabilities = CapabilitiesFromDomain(v.Capabilities)
	return out
}
func MetaToDomain(v Meta) domain.Meta {
	out := domain.Meta{}
	out.Service = v.Service
	out.Version = v.Version
	out.ContractVersion = v.ContractVersion
	out.AgentMode = v.AgentMode
	out.AllowedDataModes = make([]string, len(v.AllowedDataModes))
	for i, item := range v.AllowedDataModes {
		out.AllowedDataModes[i] = item
	}
	out.DisplayTimezone = v.DisplayTimezone
	out.SourceTimezoneStatus = v.SourceTimezoneStatus
	out.TargetUnit = v.TargetUnit
	out.NormalizationStatus = v.NormalizationStatus
	out.AgentDependency = v.AgentDependency
	out.Capabilities = CapabilitiesToDomain(v.Capabilities)
	return out
}
func TurbineFromDomain(v domain.Turbine) Turbine {
	out := Turbine{}
	out.ID = v.ID
	out.Name = v.Name
	out.Latitude = v.Latitude
	out.Longitude = v.Longitude
	if v.RatedPowerMW != nil {
		item := *v.RatedPowerMW
		out.RatedPowerMW = &item
	}
	if v.HubHeightM != nil {
		item := *v.HubHeightM
		out.HubHeightM = &item
	}
	out.MetadataStatus = v.MetadataStatus
	return out
}
func TurbineToDomain(v Turbine) domain.Turbine {
	out := domain.Turbine{}
	out.ID = v.ID
	out.Name = v.Name
	out.Latitude = v.Latitude
	out.Longitude = v.Longitude
	if v.RatedPowerMW != nil {
		item := *v.RatedPowerMW
		out.RatedPowerMW = &item
	}
	if v.HubHeightM != nil {
		item := *v.HubHeightM
		out.HubHeightM = &item
	}
	out.MetadataStatus = v.MetadataStatus
	return out
}
func ModelFromDomain(v domain.Model) Model {
	out := Model{}
	out.ModelVersion = v.ModelVersion
	out.DisplayName = v.DisplayName
	out.DataMode = v.DataMode
	out.FeatureVersion = v.FeatureVersion
	out.TrainingDataAvailableThrough = v.TrainingDataAvailableThrough.UTC()
	out.SupportsQuantiles = v.SupportsQuantiles
	out.Availability = v.Availability
	return out
}
func ModelToDomain(v Model) domain.Model {
	out := domain.Model{}
	out.ModelVersion = v.ModelVersion
	out.DisplayName = v.DisplayName
	out.DataMode = v.DataMode
	out.FeatureVersion = v.FeatureVersion
	out.TrainingDataAvailableThrough = v.TrainingDataAvailableThrough.UTC()
	out.SupportsQuantiles = v.SupportsQuantiles
	out.Availability = v.Availability
	return out
}
func ForecastRunDetailsFromDomain(v domain.ForecastRunDetails) ForecastRunDetails {
	out := ForecastRunDetails{}
	out.Job = JobRecordFromDomain(v.Job)
	out.Request = ForecastRequestFromDomain(v.Request)
	if v.ParentReplayID != nil {
		item := *v.ParentReplayID
		out.ParentReplayID = &item
	}
	out.ResultAvailable = v.ResultAvailable
	out.CancelRequested = v.CancelRequested
	return out
}
func ForecastRunDetailsToDomain(v ForecastRunDetails) domain.ForecastRunDetails {
	out := domain.ForecastRunDetails{}
	out.Job = JobRecordToDomain(v.Job)
	out.Request = ForecastRequestToDomain(v.Request)
	if v.ParentReplayID != nil {
		item := *v.ParentReplayID
		out.ParentReplayID = &item
	}
	out.ResultAvailable = v.ResultAvailable
	out.CancelRequested = v.CancelRequested
	return out
}
func ReplayCountersFromDomain(v domain.ReplayCounters) ReplayCounters {
	out := ReplayCounters{}
	out.Total = v.Total
	out.Queued = v.Queued
	out.Running = v.Running
	out.Completed = v.Completed
	out.Failed = v.Failed
	out.Cancelled = v.Cancelled
	return out
}
func ReplayCountersToDomain(v ReplayCounters) domain.ReplayCounters {
	out := domain.ReplayCounters{}
	out.Total = v.Total
	out.Queued = v.Queued
	out.Running = v.Running
	out.Completed = v.Completed
	out.Failed = v.Failed
	out.Cancelled = v.Cancelled
	return out
}
func ReplayDetailsFromDomain(v domain.ReplayDetails) ReplayDetails {
	out := ReplayDetails{}
	out.Job = JobRecordFromDomain(v.Job)
	out.Request = ReplayRequestFromDomain(v.Request)
	out.CancelRequested = v.CancelRequested
	out.Counters = ReplayCountersFromDomain(v.Counters)
	out.HasFailures = v.HasFailures
	return out
}
func ReplayDetailsToDomain(v ReplayDetails) domain.ReplayDetails {
	out := domain.ReplayDetails{}
	out.Job = JobRecordToDomain(v.Job)
	out.Request = ReplayRequestToDomain(v.Request)
	out.CancelRequested = v.CancelRequested
	out.Counters = ReplayCountersToDomain(v.Counters)
	out.HasFailures = v.HasFailures
	return out
}
func WeatherPointFromDomain(v domain.WeatherPoint) WeatherPoint {
	out := WeatherPoint{}
	out.TurbineID = v.TurbineID
	out.ValidTime = v.ValidTime.UTC()
	if v.WindSpeedMS != nil {
		item := *v.WindSpeedMS
		out.WindSpeedMS = &item
	}
	if v.WindHeightM != nil {
		item := *v.WindHeightM
		out.WindHeightM = &item
	}
	if v.TemperatureC != nil {
		item := *v.TemperatureC
		out.TemperatureC = &item
	}
	out.IsInterpolated = v.IsInterpolated
	return out
}
func WeatherPointToDomain(v WeatherPoint) domain.WeatherPoint {
	out := domain.WeatherPoint{}
	out.TurbineID = v.TurbineID
	out.ValidTime = v.ValidTime.UTC()
	if v.WindSpeedMS != nil {
		item := *v.WindSpeedMS
		out.WindSpeedMS = &item
	}
	if v.WindHeightM != nil {
		item := *v.WindHeightM
		out.WindHeightM = &item
	}
	if v.TemperatureC != nil {
		item := *v.TemperatureC
		out.TemperatureC = &item
	}
	out.IsInterpolated = v.IsInterpolated
	return out
}
func WeatherDetailsFromDomain(v domain.WeatherDetails) WeatherDetails {
	out := WeatherDetails{}
	out.RunID = v.RunID
	out.DataMode = v.DataMode
	out.Status = v.Status
	out.WeatherRuns = make([]WeatherProvenance, len(v.WeatherRuns))
	for i, item := range v.WeatherRuns {
		out.WeatherRuns[i] = WeatherProvenanceFromDomain(item)
	}
	out.Points = make([]WeatherPoint, len(v.Points))
	for i, item := range v.Points {
		out.Points[i] = WeatherPointFromDomain(item)
	}
	return out
}
func WeatherDetailsToDomain(v WeatherDetails) domain.WeatherDetails {
	out := domain.WeatherDetails{}
	out.RunID = v.RunID
	out.DataMode = v.DataMode
	out.Status = v.Status
	out.WeatherRuns = make([]domain.WeatherProvenance, len(v.WeatherRuns))
	for i, item := range v.WeatherRuns {
		out.WeatherRuns[i] = WeatherProvenanceToDomain(item)
	}
	out.Points = make([]domain.WeatherPoint, len(v.Points))
	for i, item := range v.Points {
		out.Points[i] = WeatherPointToDomain(item)
	}
	return out
}
func FeatureContributionFromDomain(v domain.FeatureContribution) FeatureContribution {
	out := FeatureContribution{}
	out.Feature = v.Feature
	out.Value = v.Value
	out.Contribution = v.Contribution
	return out
}
func FeatureContributionToDomain(v FeatureContribution) domain.FeatureContribution {
	out := domain.FeatureContribution{}
	out.Feature = v.Feature
	out.Value = v.Value
	out.Contribution = v.Contribution
	return out
}
func SHAPItemFromDomain(v domain.SHAPItem) SHAPItem {
	out := SHAPItem{}
	out.TurbineID = v.TurbineID
	out.ValidTime = v.ValidTime.UTC()
	out.Output = v.Output
	out.BaseValue = v.BaseValue
	out.Prediction = v.Prediction
	out.FeatureContributions = make([]FeatureContribution, len(v.FeatureContributions))
	for i, item := range v.FeatureContributions {
		out.FeatureContributions[i] = FeatureContributionFromDomain(item)
	}
	out.OutputUnit = v.OutputUnit
	return out
}
func SHAPItemToDomain(v SHAPItem) domain.SHAPItem {
	out := domain.SHAPItem{}
	out.TurbineID = v.TurbineID
	out.ValidTime = v.ValidTime.UTC()
	out.Output = v.Output
	out.BaseValue = v.BaseValue
	out.Prediction = v.Prediction
	out.FeatureContributions = make([]domain.FeatureContribution, len(v.FeatureContributions))
	for i, item := range v.FeatureContributions {
		out.FeatureContributions[i] = FeatureContributionToDomain(item)
	}
	out.OutputUnit = v.OutputUnit
	return out
}
func ExplanationDetailsFromDomain(v domain.ExplanationDetails) ExplanationDetails {
	out := ExplanationDetails{}
	out.RunID = v.RunID
	out.DataMode = v.DataMode
	out.Status = v.Status
	out.Text = v.Text
	out.SHAPStatus = v.SHAPStatus
	out.SHAPItems = make([]SHAPItem, len(v.SHAPItems))
	for i, item := range v.SHAPItems {
		out.SHAPItems[i] = SHAPItemFromDomain(item)
	}
	return out
}
func ExplanationDetailsToDomain(v ExplanationDetails) domain.ExplanationDetails {
	out := domain.ExplanationDetails{}
	out.RunID = v.RunID
	out.DataMode = v.DataMode
	out.Status = v.Status
	out.Text = v.Text
	out.SHAPStatus = v.SHAPStatus
	out.SHAPItems = make([]domain.SHAPItem, len(v.SHAPItems))
	for i, item := range v.SHAPItems {
		out.SHAPItems[i] = SHAPItemToDomain(item)
	}
	return out
}
func EvaluationMetricFromDomain(v domain.EvaluationMetric) EvaluationMetric {
	out := EvaluationMetric{}
	out.TurbineID = v.TurbineID
	out.LeadFrom = v.LeadFrom
	out.LeadTo = v.LeadTo
	if v.MAE != nil {
		item := *v.MAE
		out.MAE = &item
	}
	if v.RMSE != nil {
		item := *v.RMSE
		out.RMSE = &item
	}
	if v.Bias != nil {
		item := *v.Bias
		out.Bias = &item
	}
	if v.CoverageQ10Q90 != nil {
		item := *v.CoverageQ10Q90
		out.CoverageQ10Q90 = &item
	}
	if v.MeanIntervalWidth != nil {
		item := *v.MeanIntervalWidth
		out.MeanIntervalWidth = &item
	}
	return out
}
func EvaluationMetricToDomain(v EvaluationMetric) domain.EvaluationMetric {
	out := domain.EvaluationMetric{}
	out.TurbineID = v.TurbineID
	out.LeadFrom = v.LeadFrom
	out.LeadTo = v.LeadTo
	if v.MAE != nil {
		item := *v.MAE
		out.MAE = &item
	}
	if v.RMSE != nil {
		item := *v.RMSE
		out.RMSE = &item
	}
	if v.Bias != nil {
		item := *v.Bias
		out.Bias = &item
	}
	if v.CoverageQ10Q90 != nil {
		item := *v.CoverageQ10Q90
		out.CoverageQ10Q90 = &item
	}
	if v.MeanIntervalWidth != nil {
		item := *v.MeanIntervalWidth
		out.MeanIntervalWidth = &item
	}
	return out
}
func EvaluationReportFromDomain(v domain.EvaluationReport) EvaluationReport {
	out := EvaluationReport{}
	out.EvaluationID = v.EvaluationID
	out.DataMode = v.DataMode
	out.Status = v.Status
	out.ModelVersion = v.ModelVersion
	out.BaselineName = v.BaselineName
	out.TargetUnit = v.TargetUnit
	out.EvaluationScope = v.EvaluationScope
	out.PeriodStart = v.PeriodStart.UTC()
	out.PeriodEnd = v.PeriodEnd.UTC()
	out.TrainingDataAvailableThrough = v.TrainingDataAvailableThrough.UTC()
	if v.NObservations != nil {
		item := *v.NObservations
		out.NObservations = &item
	}
	out.Metrics = make([]EvaluationMetric, len(v.Metrics))
	for i, item := range v.Metrics {
		out.Metrics[i] = EvaluationMetricFromDomain(item)
	}
	out.Notes = make([]string, len(v.Notes))
	for i, item := range v.Notes {
		out.Notes[i] = item
	}
	return out
}
func EvaluationReportToDomain(v EvaluationReport) domain.EvaluationReport {
	out := domain.EvaluationReport{}
	out.EvaluationID = v.EvaluationID
	out.DataMode = v.DataMode
	out.Status = v.Status
	out.ModelVersion = v.ModelVersion
	out.BaselineName = v.BaselineName
	out.TargetUnit = v.TargetUnit
	out.EvaluationScope = v.EvaluationScope
	out.PeriodStart = v.PeriodStart.UTC()
	out.PeriodEnd = v.PeriodEnd.UTC()
	out.TrainingDataAvailableThrough = v.TrainingDataAvailableThrough.UTC()
	if v.NObservations != nil {
		item := *v.NObservations
		out.NObservations = &item
	}
	out.Metrics = make([]domain.EvaluationMetric, len(v.Metrics))
	for i, item := range v.Metrics {
		out.Metrics[i] = EvaluationMetricToDomain(item)
	}
	out.Notes = make([]string, len(v.Notes))
	for i, item := range v.Notes {
		out.Notes[i] = item
	}
	return out
}
func TurbineQualityFromDomain(v domain.TurbineQuality) TurbineQuality {
	out := TurbineQuality{}
	out.TurbineID = v.TurbineID
	if v.RangeStart != nil {
		item := v.RangeStart.UTC()
		out.RangeStart = &item
	}
	if v.RangeEnd != nil {
		item := v.RangeEnd.UTC()
		out.RangeEnd = &item
	}
	if v.RowCount != nil {
		item := *v.RowCount
		out.RowCount = &item
	}
	if v.CompleteHourCount != nil {
		item := *v.CompleteHourCount
		out.CompleteHourCount = &item
	}
	if v.MissingHourCount != nil {
		item := *v.MissingHourCount
		out.MissingHourCount = &item
	}
	out.Warnings = make([]string, len(v.Warnings))
	for i, item := range v.Warnings {
		out.Warnings[i] = item
	}
	return out
}
func TurbineQualityToDomain(v TurbineQuality) domain.TurbineQuality {
	out := domain.TurbineQuality{}
	out.TurbineID = v.TurbineID
	if v.RangeStart != nil {
		item := v.RangeStart.UTC()
		out.RangeStart = &item
	}
	if v.RangeEnd != nil {
		item := v.RangeEnd.UTC()
		out.RangeEnd = &item
	}
	if v.RowCount != nil {
		item := *v.RowCount
		out.RowCount = &item
	}
	if v.CompleteHourCount != nil {
		item := *v.CompleteHourCount
		out.CompleteHourCount = &item
	}
	if v.MissingHourCount != nil {
		item := *v.MissingHourCount
		out.MissingHourCount = &item
	}
	out.Warnings = make([]string, len(v.Warnings))
	for i, item := range v.Warnings {
		out.Warnings[i] = item
	}
	return out
}
func DataQualityReportFromDomain(v domain.DataQualityReport) DataQualityReport {
	out := DataQualityReport{}
	out.Status = v.Status
	if v.GeneratedAt != nil {
		item := v.GeneratedAt.UTC()
		out.GeneratedAt = &item
	}
	out.DataMode = v.DataMode
	if v.SourceReference != nil {
		item := *v.SourceReference
		out.SourceReference = &item
	}
	out.Turbines = make([]TurbineQuality, len(v.Turbines))
	for i, item := range v.Turbines {
		out.Turbines[i] = TurbineQualityFromDomain(item)
	}
	return out
}
func DataQualityReportToDomain(v DataQualityReport) domain.DataQualityReport {
	out := domain.DataQualityReport{}
	out.Status = v.Status
	if v.GeneratedAt != nil {
		item := v.GeneratedAt.UTC()
		out.GeneratedAt = &item
	}
	out.DataMode = v.DataMode
	if v.SourceReference != nil {
		item := *v.SourceReference
		out.SourceReference = &item
	}
	out.Turbines = make([]domain.TurbineQuality, len(v.Turbines))
	for i, item := range v.Turbines {
		out.Turbines[i] = TurbineQualityToDomain(item)
	}
	return out
}
func TurbineListFromDomain(v domain.TurbineList) TurbineList {
	out := TurbineList{}
	out.Items = make([]Turbine, len(v.Items))
	for i, item := range v.Items {
		out.Items[i] = TurbineFromDomain(item)
	}
	if v.NextCursor != nil {
		item := *v.NextCursor
		out.NextCursor = &item
	}
	return out
}
func TurbineListToDomain(v TurbineList) domain.TurbineList {
	out := domain.TurbineList{}
	out.Items = make([]domain.Turbine, len(v.Items))
	for i, item := range v.Items {
		out.Items[i] = TurbineToDomain(item)
	}
	if v.NextCursor != nil {
		item := *v.NextCursor
		out.NextCursor = &item
	}
	return out
}
func ModelListFromDomain(v domain.ModelList) ModelList {
	out := ModelList{}
	out.Items = make([]Model, len(v.Items))
	for i, item := range v.Items {
		out.Items[i] = ModelFromDomain(item)
	}
	if v.NextCursor != nil {
		item := *v.NextCursor
		out.NextCursor = &item
	}
	return out
}
func ModelListToDomain(v ModelList) domain.ModelList {
	out := domain.ModelList{}
	out.Items = make([]domain.Model, len(v.Items))
	for i, item := range v.Items {
		out.Items[i] = ModelToDomain(item)
	}
	if v.NextCursor != nil {
		item := *v.NextCursor
		out.NextCursor = &item
	}
	return out
}
func ForecastListFromDomain(v domain.ForecastList) ForecastList {
	out := ForecastList{}
	out.Items = make([]ForecastRunDetails, len(v.Items))
	for i, item := range v.Items {
		out.Items[i] = ForecastRunDetailsFromDomain(item)
	}
	if v.NextCursor != nil {
		item := *v.NextCursor
		out.NextCursor = &item
	}
	return out
}
func ForecastListToDomain(v ForecastList) domain.ForecastList {
	out := domain.ForecastList{}
	out.Items = make([]domain.ForecastRunDetails, len(v.Items))
	for i, item := range v.Items {
		out.Items[i] = ForecastRunDetailsToDomain(item)
	}
	if v.NextCursor != nil {
		item := *v.NextCursor
		out.NextCursor = &item
	}
	return out
}
func EvaluationListFromDomain(v domain.EvaluationList) EvaluationList {
	out := EvaluationList{}
	out.Items = make([]EvaluationReport, len(v.Items))
	for i, item := range v.Items {
		out.Items[i] = EvaluationReportFromDomain(item)
	}
	if v.NextCursor != nil {
		item := *v.NextCursor
		out.NextCursor = &item
	}
	return out
}
func EvaluationListToDomain(v EvaluationList) domain.EvaluationList {
	out := domain.EvaluationList{}
	out.Items = make([]domain.EvaluationReport, len(v.Items))
	for i, item := range v.Items {
		out.Items[i] = EvaluationReportToDomain(item)
	}
	if v.NextCursor != nil {
		item := *v.NextCursor
		out.NextCursor = &item
	}
	return out
}
func HealthFromDomain(v domain.Health) Health {
	out := Health{}
	out.Status = v.Status
	return out
}
func HealthToDomain(v Health) domain.Health {
	out := domain.Health{}
	out.Status = v.Status
	return out
}
func StreamEndFromDomain(v domain.StreamEnd) StreamEnd {
	out := StreamEnd{}
	out.JobID = v.JobID
	out.Status = v.Status
	return out
}
func StreamEndToDomain(v StreamEnd) domain.StreamEnd {
	out := domain.StreamEnd{}
	out.JobID = v.JobID
	out.Status = v.Status
	return out
}
