// Code generated by tools/generate_contract.py; DO NOT EDIT.
package agenthttp

import "time"

type ForecastRequest struct {
 ForecastOrigin time.Time `json:"forecast_origin"`
 HorizonHours int `json:"horizon_hours"`
 TurbineIDs []int `json:"turbine_ids"`
 ModelVersion string `json:"model_version"`
 Mode string `json:"mode"`
 DataMode string `json:"data_mode"`
}

type ReplayRequest struct {
 Origins []time.Time `json:"origins"`
 HorizonHours int `json:"horizon_hours"`
 TurbineIDs []int `json:"turbine_ids"`
 ModelVersion string `json:"model_version"`
 DataMode string `json:"data_mode"`
}

type JobRecord struct {
 JobID string `json:"job_id"`
 JobType string `json:"job_type"`
 Status string `json:"status"`
 CreatedAt time.Time `json:"created_at"`
 UpdatedAt time.Time `json:"updated_at"`
 Stage string `json:"stage"`
 ErrorCode *string `json:"error_code"`
 ErrorMessage *string `json:"error_message"`
}

type ForecastPoint struct {
 TurbineID int `json:"turbine_id"`
 ValidTime time.Time `json:"valid_time"`
 IntervalEnd time.Time `json:"interval_end"`
 LeadHours int `json:"lead_hours"`
 PowerMean float64 `json:"power_mean"`
 Q10 float64 `json:"q10"`
 Q50 float64 `json:"q50"`
 Q90 float64 `json:"q90"`
}

type WeatherProvenance struct {
 Provider string `json:"provider"`
 RunID string `json:"run_id"`
 InitializationTime time.Time `json:"initialization_time"`
 EffectiveAvailableAt time.Time `json:"effective_available_at"`
 AvailabilityBasis string `json:"availability_basis"`
 AvailabilityPolicyID *string `json:"availability_policy_id"`
 RetrievedAt time.Time `json:"retrieved_at"`
 SourceReference string `json:"source_reference"`
 ContentSHA256 string `json:"content_sha256"`
}

type ForecastResult struct {
 RunID string `json:"run_id"`
 ForecastOrigin time.Time `json:"forecast_origin"`
 HorizonHours int `json:"horizon_hours"`
 TurbineIDs []int `json:"turbine_ids"`
 DataMode string `json:"data_mode"`
 ModelVersion string `json:"model_version"`
 FeatureVersion string `json:"feature_version"`
 TrainingDataAvailableThrough time.Time `json:"training_data_available_through"`
 QualityStatus string `json:"quality_status"`
 ExplanationStatus string `json:"explanation_status"`
 Explanation string `json:"explanation"`
 Warnings []string `json:"warnings"`
 WeatherRuns []WeatherProvenance `json:"weather_runs"`
 Points []ForecastPoint `json:"points"`
}

type AgentEvent struct {
 EventID int64 `json:"event_id"`
 JobID string `json:"job_id"`
 RecordedAt time.Time `json:"recorded_at"`
 Kind string `json:"kind"`
 Node string `json:"node"`
 Message string `json:"message"`
 EvidenceRefs []string `json:"evidence_refs"`
}

type ApiError struct {
 Code string `json:"code"`
 Message string `json:"message"`
 RequestID *string `json:"request_id"`
}

type Capabilities struct {
 Forecast bool `json:"forecast"`
 Replay bool `json:"replay"`
 Cancel bool `json:"cancel"`
 SSE bool `json:"sse"`
 WeatherDetails bool `json:"weather_details"`
 SHAP bool `json:"shap"`
 Evaluations bool `json:"evaluations"`
 DataQuality bool `json:"data_quality"`
 Simulated bool `json:"simulated"`
}

type Meta struct {
 Service string `json:"service"`
 Version string `json:"version"`
 ContractVersion string `json:"contract_version"`
 AgentMode string `json:"agent_mode"`
 AllowedDataModes []string `json:"allowed_data_modes"`
 DisplayTimezone string `json:"display_timezone"`
 SourceTimezoneStatus string `json:"source_timezone_status"`
 TargetUnit string `json:"target_unit"`
 NormalizationStatus string `json:"normalization_status"`
 AgentDependency string `json:"agent_dependency"`
 Capabilities Capabilities `json:"capabilities"`
}

type Turbine struct {
 ID int `json:"id"`
 Name string `json:"name"`
 Latitude float64 `json:"latitude"`
 Longitude float64 `json:"longitude"`
 RatedPowerMW *float64 `json:"rated_power_mw"`
 HubHeightM *float64 `json:"hub_height_m"`
 MetadataStatus string `json:"metadata_status"`
}

type Model struct {
 ModelVersion string `json:"model_version"`
 DisplayName string `json:"display_name"`
 DataMode string `json:"data_mode"`
 FeatureVersion string `json:"feature_version"`
 TrainingDataAvailableThrough time.Time `json:"training_data_available_through"`
 SupportsQuantiles bool `json:"supports_quantiles"`
 Availability string `json:"availability"`
}

type ForecastRunDetails struct {
 Job JobRecord `json:"job"`
 Request ForecastRequest `json:"request"`
 ParentReplayID *string `json:"parent_replay_id"`
 ResultAvailable bool `json:"result_available"`
 CancelRequested bool `json:"cancel_requested"`
}

type ReplayCounters struct {
 Total int `json:"total"`
 Queued int `json:"queued"`
 Running int `json:"running"`
 Completed int `json:"completed"`
 Failed int `json:"failed"`
 Cancelled int `json:"cancelled"`
}

type ReplayDetails struct {
 Job JobRecord `json:"job"`
 Request ReplayRequest `json:"request"`
 CancelRequested bool `json:"cancel_requested"`
 Counters ReplayCounters `json:"counters"`
 HasFailures bool `json:"has_failures"`
}

type WeatherPoint struct {
 TurbineID int `json:"turbine_id"`
 ValidTime time.Time `json:"valid_time"`
 WindSpeedMS *float64 `json:"wind_speed_ms"`
 WindHeightM *float64 `json:"wind_height_m"`
 TemperatureC *float64 `json:"temperature_c"`
 IsInterpolated bool `json:"is_interpolated"`
}

type WeatherDetails struct {
 RunID string `json:"run_id"`
 DataMode string `json:"data_mode"`
 Status string `json:"status"`
 WeatherRuns []WeatherProvenance `json:"weather_runs"`
 Points []WeatherPoint `json:"points"`
}

type FeatureContribution struct {
 Feature string `json:"feature"`
 Value float64 `json:"value"`
 Contribution float64 `json:"contribution"`
}

type SHAPItem struct {
 TurbineID int `json:"turbine_id"`
 ValidTime time.Time `json:"valid_time"`
 Output string `json:"output"`
 BaseValue float64 `json:"base_value"`
 Prediction float64 `json:"prediction"`
 FeatureContributions []FeatureContribution `json:"feature_contributions"`
 OutputUnit string `json:"output_unit"`
}

type ExplanationDetails struct {
 RunID string `json:"run_id"`
 DataMode string `json:"data_mode"`
 Status string `json:"status"`
 Text string `json:"text"`
 SHAPStatus string `json:"shap_status"`
 SHAPItems []SHAPItem `json:"shap_items"`
}

type EvaluationMetric struct {
 TurbineID int `json:"turbine_id"`
 LeadFrom int `json:"lead_from"`
 LeadTo int `json:"lead_to"`
 MAE *float64 `json:"mae"`
 RMSE *float64 `json:"rmse"`
 Bias *float64 `json:"bias"`
 CoverageQ10Q90 *float64 `json:"coverage_q10_q90"`
 MeanIntervalWidth *float64 `json:"mean_interval_width"`
}

type EvaluationReport struct {
 EvaluationID string `json:"evaluation_id"`
 DataMode string `json:"data_mode"`
 Status string `json:"status"`
 ModelVersion string `json:"model_version"`
 BaselineName string `json:"baseline_name"`
 TargetUnit string `json:"target_unit"`
 EvaluationScope string `json:"evaluation_scope"`
 PeriodStart time.Time `json:"period_start"`
 PeriodEnd time.Time `json:"period_end"`
 TrainingDataAvailableThrough time.Time `json:"training_data_available_through"`
 NObservations *int `json:"n_observations"`
 Metrics []EvaluationMetric `json:"metrics"`
 Notes []string `json:"notes"`
}

type TurbineQuality struct {
 TurbineID int `json:"turbine_id"`
 RangeStart *time.Time `json:"range_start"`
 RangeEnd *time.Time `json:"range_end"`
 RowCount *int `json:"row_count"`
 CompleteHourCount *int `json:"complete_hour_count"`
 MissingHourCount *int `json:"missing_hour_count"`
 Warnings []string `json:"warnings"`
}

type DataQualityReport struct {
 Status string `json:"status"`
 GeneratedAt *time.Time `json:"generated_at"`
 DataMode string `json:"data_mode"`
 SourceReference *string `json:"source_reference"`
 Turbines []TurbineQuality `json:"turbines"`
}

type TurbineList struct {
 Items []Turbine `json:"items"`
 NextCursor *string `json:"next_cursor"`
}

type ModelList struct {
 Items []Model `json:"items"`
 NextCursor *string `json:"next_cursor"`
}

type ForecastList struct {
 Items []ForecastRunDetails `json:"items"`
 NextCursor *string `json:"next_cursor"`
}

type EvaluationList struct {
 Items []EvaluationReport `json:"items"`
 NextCursor *string `json:"next_cursor"`
}

type Health struct {
 Status string `json:"status"`
}

type StreamEnd struct {
 JobID string `json:"job_id"`
 Status string `json:"status"`
}

