// Code generated by tools/generate_contract.py; DO NOT EDIT.
package domain

import "time"

type ForecastRequest struct {
	ForecastOrigin time.Time
	HorizonHours   int
	TurbineIDs     []int
	ModelVersion   string
	Mode           string
	DataMode       string
}

type ReplayRequest struct {
	Origins      []time.Time
	HorizonHours int
	TurbineIDs   []int
	ModelVersion string
	DataMode     string
}

type JobRecord struct {
	JobID        string
	JobType      string
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Stage        string
	ErrorCode    *string
	ErrorMessage *string
}

type ForecastPoint struct {
	TurbineID   int
	ValidTime   time.Time
	IntervalEnd time.Time
	LeadHours   int
	PowerMean   float64
	Q10         float64
	Q50         float64
	Q90         float64
}

type WeatherProvenance struct {
	Provider             string
	RunID                string
	InitializationTime   time.Time
	EffectiveAvailableAt time.Time
	AvailabilityBasis    string
	AvailabilityPolicyID *string
	RetrievedAt          time.Time
	SourceReference      string
	ContentSHA256        string
}

type ForecastResult struct {
	RunID                        string
	ForecastOrigin               time.Time
	HorizonHours                 int
	TurbineIDs                   []int
	DataMode                     string
	ModelVersion                 string
	FeatureVersion               string
	TrainingDataAvailableThrough time.Time
	QualityStatus                string
	ExplanationStatus            string
	Explanation                  string
	Warnings                     []string
	WeatherRuns                  []WeatherProvenance
	Points                       []ForecastPoint
}

type AgentEvent struct {
	EventID      int64
	JobID        string
	RecordedAt   time.Time
	Kind         string
	Node         string
	Message      string
	EvidenceRefs []string
}

type ApiError struct {
	Code      string
	Message   string
	RequestID *string
}

type Capabilities struct {
	Forecast       bool
	Replay         bool
	Cancel         bool
	SSE            bool
	WeatherDetails bool
	SHAP           bool
	Evaluations    bool
	DataQuality    bool
	Simulated      bool
}

type Meta struct {
	Service              string
	Version              string
	ContractVersion      string
	AgentMode            string
	AllowedDataModes     []string
	DisplayTimezone      string
	SourceTimezoneStatus string
	TargetUnit           string
	NormalizationStatus  string
	AgentDependency      string
	Capabilities         Capabilities
}

type Turbine struct {
	ID             int
	Name           string
	Latitude       float64
	Longitude      float64
	RatedPowerMW   *float64
	HubHeightM     *float64
	MetadataStatus string
}

type Model struct {
	ModelVersion                 string
	DisplayName                  string
	DataMode                     string
	FeatureVersion               string
	TrainingDataAvailableThrough time.Time
	SupportsQuantiles            bool
	Availability                 string
}

type ForecastRunDetails struct {
	Job             JobRecord
	Request         ForecastRequest
	ParentReplayID  *string
	ResultAvailable bool
	CancelRequested bool
}

type ReplayCounters struct {
	Total     int
	Queued    int
	Running   int
	Completed int
	Failed    int
	Cancelled int
}

type ReplayDetails struct {
	Job             JobRecord
	Request         ReplayRequest
	CancelRequested bool
	Counters        ReplayCounters
	HasFailures     bool
}

type WeatherPoint struct {
	TurbineID      int
	ValidTime      time.Time
	WindSpeedMS    *float64
	WindHeightM    *float64
	TemperatureC   *float64
	IsInterpolated bool
}

type WeatherDetails struct {
	RunID       string
	DataMode    string
	Status      string
	WeatherRuns []WeatherProvenance
	Points      []WeatherPoint
}

type FeatureContribution struct {
	Feature      string
	Value        float64
	Contribution float64
}

type SHAPItem struct {
	TurbineID            int
	ValidTime            time.Time
	Output               string
	BaseValue            float64
	Prediction           float64
	FeatureContributions []FeatureContribution
	OutputUnit           string
}

type ExplanationDetails struct {
	RunID      string
	DataMode   string
	Status     string
	Text       string
	SHAPStatus string
	SHAPItems  []SHAPItem
}

type EvaluationMetric struct {
	TurbineID         int
	LeadFrom          int
	LeadTo            int
	MAE               *float64
	RMSE              *float64
	Bias              *float64
	CoverageQ10Q90    *float64
	MeanIntervalWidth *float64
}

type EvaluationReport struct {
	EvaluationID                 string
	DataMode                     string
	Status                       string
	ModelVersion                 string
	BaselineName                 string
	TargetUnit                   string
	EvaluationScope              string
	PeriodStart                  time.Time
	PeriodEnd                    time.Time
	TrainingDataAvailableThrough time.Time
	NObservations                *int
	Metrics                      []EvaluationMetric
	Notes                        []string
}

type TurbineQuality struct {
	TurbineID         int
	RangeStart        *time.Time
	RangeEnd          *time.Time
	RowCount          *int
	CompleteHourCount *int
	MissingHourCount  *int
	Warnings          []string
}

type DataQualityReport struct {
	Status          string
	GeneratedAt     *time.Time
	DataMode        string
	SourceReference *string
	Turbines        []TurbineQuality
}

type TurbineList struct {
	Items      []Turbine
	NextCursor *string
}

type ModelList struct {
	Items      []Model
	NextCursor *string
}

type ForecastList struct {
	Items      []ForecastRunDetails
	NextCursor *string
}

type EvaluationList struct {
	Items      []EvaluationReport
	NextCursor *string
}

type Health struct {
	Status string
}

type StreamEnd struct {
	JobID  string
	Status string
}
