package agentmock

import("context";"time";"wind/backend/internal/domain")
func(a *Adapter) Models(context.Context)(domain.ModelList,error){return domain.ModelList{Items:[]domain.Model{{ModelVersion:"fixture-not-trained",DisplayName:"Synthetic fixture (not trained)",DataMode:"fixture",FeatureVersion:"fixture-features-v1",TrainingDataAvailableThrough:time.Date(2023,3,1,0,0,0,0,time.UTC),SupportsQuantiles:true,Availability:"ready"}}},nil}
func(a *Adapter) Weather(_ context.Context,id string)(domain.WeatherDetails,error){a.mu.Lock();defer a.mu.Unlock();r,e:=a.find(id,"forecast");if e!=nil{return domain.WeatherDetails{},e};if r.weather==nil{return domain.WeatherDetails{},domain.Err("RESULT_NOT_READY","Weather artifact not published")};return clone(*r.weather),nil}
func(a *Adapter) Explanation(ctx context.Context,id string)(domain.ExplanationDetails,error){r,e:=a.ForecastResult(ctx,id);if e!=nil{return domain.ExplanationDetails{},e};return domain.ExplanationDetails{RunID:id,DataMode:"fixture",Status:r.ExplanationStatus,Text:r.Explanation,SHAPStatus:"unavailable",SHAPItems:[]domain.SHAPItem{}},nil}
func(a *Adapter) evaluation(id string)domain.EvaluationReport{n:=96;mae,rmse,bias,coverage,width:=0.12,0.16,0.01,0.8,0.3;r:=domain.EvaluationReport{EvaluationID:id,DataMode:"fixture",Status:"available",ModelVersion:"fixture-not-trained",BaselineName:"fixture-persistence-not-measured",TargetUnit:"normalized_power",EvaluationScope:"end_to_end",PeriodStart:time.Date(2026,1,1,0,0,0,0,time.UTC),PeriodEnd:time.Date(2026,1,3,0,0,0,0,time.UTC),TrainingDataAvailableThrough:time.Date(2025,12,31,0,0,0,0,time.UTC),NObservations:&n,Metrics:[]domain.EvaluationMetric{},Notes:[]string{"MOCK: Synthetic UI example; no model evaluation was performed"}};for _,t:=range []int{1,2}{r.Metrics=append(r.Metrics,domain.EvaluationMetric{TurbineID:t,LeadFrom:1,LeadTo:48,MAE:&mae,RMSE:&rmse,Bias:&bias,CoverageQ10Q90:&coverage,MeanIntervalWidth:&width})};if id=="fixture-evaluation-unavailable"{r.Status="unavailable";r.NObservations=nil;for i:=range r.Metrics{r.Metrics[i].MAE=nil;r.Metrics[i].RMSE=nil;r.Metrics[i].Bias=nil;r.Metrics[i].CoverageQ10Q90=nil;r.Metrics[i].MeanIntervalWidth=nil}};return r}
func(a *Adapter) Evaluation(_ context.Context,id string)(domain.EvaluationReport,error){if id!="fixture-evaluation-001"&&id!="fixture-evaluation-unavailable"{return domain.EvaluationReport{},domain.Err("NOT_FOUND","Evaluation not found")};return a.evaluation(id),nil}
func(a *Adapter) Evaluations(_ context.Context,f domain.ListFilter)(domain.EvaluationList,error){items:=[]domain.EvaluationReport{a.evaluation("fixture-evaluation-001"),a.evaluation("fixture-evaluation-unavailable")};start:=0;filter:=fingerprint(f.FilterKey());if f.Cursor!=""{c,e:=decodeCursor(f.Cursor,filter);if e!=nil{return domain.EvaluationList{},e};if c.ID!="fixture-evaluation-001"{return domain.EvaluationList{},domain.Err("INVALID_CURSOR","Invalid evaluation cursor")};start=1};out:=domain.EvaluationList{Items:[]domain.EvaluationReport{}};for i:=start;i<len(items);i++{if len(out.Items)==f.Limit{v:=encodeCursor(cursor{filter,items[i-1].EvaluationID,items[i-1].PeriodStart});out.NextCursor=&v;break};out.Items=append(out.Items,items[i])};return out,nil}
func(a *Adapter) DataQuality(context.Context)(domain.DataQualityReport,error){ts:=time.Date(2026,1,31,0,0,0,0,time.UTC);source:="fixture://data-quality/v1";r:=domain.DataQualityReport{Status:"available",GeneratedAt:&ts,DataMode:"fixture",SourceReference:&source,Turbines:[]domain.TurbineQuality{}};for _,t:=range []int{1,2}{rows,complete,missing:=144,24,0;start,end:=ts.Add(-24*time.Hour),ts;r.Turbines=append(r.Turbines,domain.TurbineQuality{TurbineID:t,RangeStart:&start,RangeEnd:&end,RowCount:&rows,CompleteHourCount:&complete,MissingHourCount:&missing,Warnings:[]string{"MOCK: Synthetic audit example; SCADA not inspected; source timezone unconfirmed"}})};return r,nil}
